### ISSUE TITLE
Feature Request: Set Gate (Width) lenght of a Step should go from 32th to at least one bar

### ISSUE THREAD

**Issue by artqcid** [raspy135/Qun-mk2#10]
Hi. In the Moment it is not possible in Step Mode to set the Gate length of a Step confortable. The Value goes from -5 to 20. This doesnt give any information in Terms of Rythmic. Maybe it would be better to set the range from very short 32th to at least one bar. In the Moment it is not possibe to set a note with duration of one bar in the sequencer. Only in live record mode. Maybe also rename "Widh" with "Gate" because this would be an more common description of a note lenght. Any toughts?

**Comment by raspy135** [comment]
When the length is long enough and the next step is also on, the note will be played as tie.

**Comment by artqcid** [comment]
Yeah but it needs to much notes to do a one bar note. I think there is no need to set many notes only to have one note with gate length of a bar. Because I regonized that playing a note with one bar length in Realtime rec mode is possible (and then there is a big width value) it should also be possible to set it manually in step mode as long as it needs.

**Comment by artqcid** [comment]
Think of it if I only use one Note with a length of a bar but do LFO Random Cutoff or anything else in Bpm Sync. This gives a nice sequence over a bar only with one note is set. Its more confusing to see 4 or 8 Notes in the Sequencer which are tied together but only hear one Note with length of one bar. Tie Notes is good if the Notes have different Values. But seeing 8 Notes with value "C2" but only hear one long note is not usefull

**Comment by raspy135** [comment]
I don't want to increase the adjustable range, it will be harder to adjust value.
I'll think about it if I can figure out the way to enter longer note.

**Comment by artqcid** [comment]
Ok I see your point of the reduced value range. Maybe introduce only in the last let's say 10 % of the Knob Range the fixed values 1, 2, 4, 8 Steps length.

**Comment by raspy135** [comment]
Hi I widened the adjustable range of width at v4.29 firmware.
