### ISSUE TITLE
Feature Request: Catch Mode for Potentiometer

### ISSUE THREAD

**Issue by artqcid** [raspy135/Qun-mk2#11]
To avoid parameter jumps by using the Poti on the Unit it would be very good to have an Catch Mode. So the parameter gets only changed if the Poti reaches the last set value.

**Comment by raspy135** [comment]
There is a kind of catch mode. Long press the parameter until it shows parameter name, then press NO or OK to move the parameter by one. This disables parameter change by turning the dial.
However when dial matches the current parameter value, "*" mark shown.
Release the parameter button and now you can change the parameter by dial. No parameter jumping.

I think the steps are too long. Another way it press 1-8 button and press NO or OK to change parameter by one, and this will disable dial so you can catch the parameter value. But there are no indicators tell you it's caught.

**Comment by artqcid** [comment]
Maybe possible to Highlight the Parameter as long it is not matched with the Poti? And end highlighting if the values are reached? (Or vice versa) I see that when I choose Cutoff ad an example, the Value gets highlighted. Maybe use this method to show catched values. 
For me the solutions with holding or/and pressing keys are not so intuitive. Realtime Tweaking is more useable with Poti. Catch Mode on synths without Rotary encoders works very well.

**Comment by raspy135** [comment]
What's Poti?
I personally fine with rough catching. For example, when I enter to VCF mode, I can see the parameter value, and I just set dial to around the value, then hit button 1 to start the adjustment.
Sometimes it's a bit off but it's ok for me.

I understand someone prefers catch mode. Let me think what I can do, but it won't be high priority for now.

**Comment by artqcid** [comment]
It is impossible to set the Value of the Poti (Potentiometer, Knob) only because of a Number in the Display. Different Parameters have different Value Ranges. Setting them only because of a Number on the Display before activating is nearly impossible and always needs a button press here and there. Why not implement a catch mode? That's only comparing two values and don't change the as long they are not the same? What speaks against a catch mode. I think there was a reason why nearly all Synths before Rotary Encoders were introduced had Catch Mode. 
I am thankful that you consider your workarounds with button pressing and holding etc.... 
But my Request is an improvement on workflow. A catch mode makes handling simpler and as long there is no technical limititation (don't think there is one) it should be considered for the future

**Comment by artqcid** [comment]
But for now, thanks very much for thinking about thus request!!!

**Comment by raspy135** [comment]
I added relative mode, which might be a good workaround.

**Comment by raspy135** [comment]
Double click to activate relative mode.

**Comment by artqcid** [comment]
That's awesome!!!!! Thx so much!!!!

**Comment by epsilonradius** [comment]
Second request for pass thru/ latch on potentiometer, having values change to max or min on any change is rough and major blocker for live playing.
Much appreciated

**Comment by raspy135** [comment]
Double click on the parameter to activate relative mode, that's current solution. I don't have a plan to add catch mode, but thanks for your feedback, I'll consider it
