### ISSUE TITLE
Midi recieve channel selection in settings

### ISSUE THREAD

**Issue by Vulkits** [raspy135/Qun-mk2#12]
Does not prevent Qun2 from receiving on midi channel 1 still. 

Notes sent from my launchpad pro mk3 via trs midi cable on midi channel 1 are still heard by the qun when the setting is set to recieve from another midi channel. Have not tried with another device, but other devices plugged into do not have this issue.

**Comment by raspy135** [comment]
It's done on purpose but I think I misread midi spec. I'll fix it.

**Comment by raspy135** [comment]
It should be fixed by v4.15 firmware. Please reopen if you still see the issue.

**Comment by Vulkits** [comment]
Oh cool! Thanks awesome news! Thanks


________________________________
