### ISSUE TITLE
Feature Request: Easy way to preview samples when importing to granular

### ISSUE THREAD

**Issue by radamJ** [raspy135/Qun-mk2#15]
One of the things that I am using the Qun for is to sequence drum samples using the Granular mode. I have a lot of drum samples in a folder on the SD card. After pressing load, it would be great if pressing the Looper Play button when in the list of files would play the currently selected file. This would make it really easy to go through the folder and preview the samples before choosing the one I want to import. Currently, pressing the play button plays what is already imported into Granular. Since I can't preview a sample, it is a couple extra steps to hear each drum sample before I settle on a particular one.

This would help my workflow and hopefully be useful to others that use Granular and have lots of samples!

**Comment by raspy135** [comment]
Hi,
You can preview the sound by SHIFT+OK when you are selecting files. It works on Granular or looper import.

**Comment by radamJ** [comment]
Oh that's great! I missed that in the manual, thanks!
