### ISSUE TITLE
INITIALIZE tone preset does not zero changed VCF settings

### ISSUE THREAD

**Issue by nrichards** [raspy135/Qun-mk2#24]
Minor bug, v5.00 (also 4.99), INITIALIZE tone preset unexpectedly does not zero changed VCF settings (e.g. "84:VCF LFO Volume") when "Extra:ON".

# Set-up

1. Turn on
2. Plug live audio / radio to LINE IN. 
3. Set "AUX:LINE IN(2CH)" with SYSTEM : System > B1 + turn dial
4. Set "LINE in THRU:ON" with SYSTEM : System > B6 + turn dial
5. Hear live audio streaming through LINE OUT
6. Set “Extra:ON” with MODE PLAY + NO
7. Set "VCFVol:70" (approximately) with SYSTEM + turn dial

# Repro

8. Go to VCF with PARAM > SHIFT + B7. Notice screen shows default values: 0’s and horizontal lines.
9. Alter VCF parameter with B8 + turn dial. See screen values change as dial turns. Live audio will be modified by Qun. 
10. INITIALIZE tone preset with SHIFT + MODE PARAM > OK > OK
11. See screen change VCF parameters to default values, as expected
12. **Hear live audio unexpectedly continue to be modified by Qun.**

# Expected

Hear unmodified audio, like in step 5.

**Comment by raspy135** [comment]
Extra processing and setting AUX L/R are two different things. Extra Processing won't turn off when initialized preset is performed. Probably it's confusing behavior, I can make a change to turn off Extra Processing when preset is initialized.

**Comment by nrichards** [comment]
> Extra processing and setting AUX L/R are two different things. Extra Processing won't turn off when initialized preset is performed.

I see - so when EP is OFF, and when the preset is initialized, the oscillators are reset:

<img width="831" alt="image" src="https://github.com/raspy135/Qun-mk2/assets/704698/3f7ed165-a819-4b40-9106-d3f570c3f310">

Alternatively when EP is ON, the mixer, VCF .... through to compressor are **not** initialized.

<img width="661" alt="image" src="https://github.com/raspy135/Qun-mk2/assets/704698/6bd64a3a-cf61-4970-b082-48c2a625e49f">
 
I was confused when the mixer, VCF ... compressor **screens** were initialized by the command, with EP ON, and the audio was not initialized.

**Comment by raspy135** [comment]
Oscillators are turned off (ignored) when EP is on.

**Comment by nrichards** [comment]
> Oscillators are turned off (ignored) when EP is on.

That makes sense to me.

I think there still could be a bug, because for me the "reset audio" is unpredictable.

* Sometimes INITIALIZE does reset audio, sometimes is does not.
* Note: INITIALIZE **always resets the user interface**. 

So it makes sense visually but not auditorily, to me.

I am investigating and cannot reproducing this 100% - but will share a video of the 'unexpected' behavior, https://www.youtube.com/watch?v=6psost2JVMo (note - I say "period" at the end accidentally ... i dictate to Google a lot and it is simply a habit of mine)

**Comment by raspy135** [comment]
thanks for the video that's a bug! I'll fix it.

**Comment by raspy135** [comment]
Fixed. it will be released in the next firmware.

**Comment by nrichards** [comment]
Thank you for helping me better identify the bug, and for continuing to make the Qun more and more fun to play with. <3

**Comment by nrichards** [comment]
Confirmed fixed in [5.01](../blob/main/firmware/qunmk2_v501.zip).
