### ISSUE TITLE
Tape wobble FX stops after 3 minutes

### ISSUE THREAD

**Issue by nrichards** [raspy135/Qun-mk2#25]
With the new experimental tape wobble (https://discord.com/channels/943680685934248006/943680686458548267/1225945880729878530), after three minutes it appears to stop having an effect.

Firmware 5.01

# Repro 1 - 3 minutes

1. Enable extra processing + line-in through on
1. Start an audio source on line-in. I use a youtube video as it conveniently shows the elapsed time. Hear clean audio.
2. Enable Tape effect with PARAM then SHIFT + B3 then B4 + dial, B5 + dial, B6 + dial, B7 + dial. Hear effected audio.
3. Wait 3 minutes or 180 seconds
4. Hear clean audio.

# Repro 2 - 75 seconds

1. Follow the steps of Repro 1, **except for**: change the "S" Effect Speed continuously 
2. Continue for 75 seconds
3. Hear partially broken effect - S value creates "stair step" effected sound, instead of the starting continuously effected sound
4. Wait for the remaining time to make 3 minutes - no turning
5. Hear differently broken effect, similar to Repro 1.

## Mitigation

* To "fix" this, after that, one must RAISE the Effect Speed. NOTICE that lowering the speed "breaks" the effect again.
* To more permanently "fix" this, after that, change the effect to OFF and RSVD and a variety of other effects. This appears to "reset" the system. After 3 minutes back on Tape, the issue will recur.

## Observations

* Many other effects are broken after breaking from 3 minutes in Tape mode.

## Open questions

* It is untested if modifying the Tape Effect settings during the 3 minute time window will elongate the "working" window.
* ~It is untested if ALL effects now have a 3 minute time window, or only the Tape effect~
  * Bitcrusher OK after 3 minutes
  * Airplane 1 OK after 3 minutes
  * Delay 1 OK after 3 minutes

# Media

* After "break", play with "fix" and "break again - notice Lowering the speed breaks
  * https://www.youtube.com/shorts/KKWf5oukHtk

**Comment by raspy135** [comment]
Thank for the report.
This should be fixed in 5.02 firmware.

**Comment by nrichards** [comment]
> Thank for the report. This should be fixed in 5.02 firmware.

Yeah! The FX is continuing beyond that 3 minute time cut-off with 5.02. Thank you!!
