### ISSUE TITLE
Expose Sequencer/Looper Parameters

### ISSUE THREAD

**Issue by benjgrad** [raspy135/Qun-mk2#3]
Feature request for exposing the Sequencer/Looper parameters through MIDI in/out.

**Comment by raspy135** [comment]
I just started to consider adding this.
All MIDI CC is already used by the synth engine. Would it be another MIDI channel just for sequencer/looper? Any ideas?

Implemented by program change is also possible but I see many controllers can't send program change messages.

**Comment by artqcid** [comment]
IMO another Midichannel would do the trick, because we can see this as another engine. As mentioned Program Change is not always implemented or usable on different Sequencers.

**Comment by benjgrad** [comment]
I agree that a different channel would be the way I would prefer it. I don't know how all midi controllers work, but by default the Novation Launchkey mini mk1 sends drum pads on a different channel, and I think it would be nice to be able to start/stop/overdub loops with drum pads.

**Comment by benjgrad** [comment]
New idea on how to handle looper/sequencer midi commands: On the qun, there's different modes... why not give the option of changing midi input modes? If you have sequencer/looper midi controls enabled, you could use the qun to change between midi input modes

**Comment by raspy135** [comment]
v4.37 firmware enables to control sequencer pattern or looper parameters via MIDI.

**Comment by raspy135** [comment]
Probably you are not interested it anymore so closing.
