### ISSUE TITLE
Stuck in Update Mode

### ISSUE THREAD

**Issue by artqcid** [raspy135/Qun-mk2#4]
After Updating to 4.04 the device Shows "Done". But After Reset (or Power off, On) the Device starts Update Process Again without Pressing any Key while Power on.

**Comment by raspy135** [comment]
It might be you used broken .bin image. Please download zip file (not bin file) and extract the image from the zip, copy it to SD card's root folder and try it again?

**Comment by artqcid** [comment]
Ok. But what i see all Zip Files in the Firmware Folders are empty. if you download a zip and try to unzip it shows Error. If i double Click on the Zip (to see content) it shows empty Folder. No Binaries inside

**Comment by artqcid** [comment]
Sorry, my fault. Its there. I try it

**Comment by artqcid** [comment]
Its working with the Zip Version. Thx! Can be closed
