### ISSUE TITLE
Looper lose lenght information from Loops (get out of Sync)

### ISSUE THREAD

**Issue by artqcid** [raspy135/Qun-mk2#5]
Firmware 4.04
I have 3 Scenes where i have 1 Loop per Scene on Track A.
After changing Scenes while playing sometimes, the Looplengt isnt in Sync with the Sequencer anymore.
I have Loops with vocals and they have Silence at the last 2 or 3 Steps.
The Loops are exactly 2 Bars Long and prepared in the correct tempo.
If a import the loops, at the beginning they start always at the first Step (as they should).
But after a while (switching between Scenes) they are like shortend. it seems they are not 2 Bars long anymore.
One sample has audio exactly 2 bars, and that sample get not shortend. The other two where audible data are not till the end of two bars seems to get shortend.
This behavour stays also if i Turn the Qun Off and On and reload the session.
Only reimporting the loops is helping. For a while the Loops are good, but without any repdroducing action the same failure occurs.
I will do my best to find some action that maybe is the reason, but meanwhile i cannot reproduce it by a dedicated action.

**Comment by raspy135** [comment]
It sounds like a bug, but it looks hard to reproduce. If you hit the issue next time, can yo send me a whole session files to me?

**Comment by artqcid** [comment]
I will do!

**Comment by raspy135** [comment]
Just FYI Looper does NOT have the BPM information in it. Looper is always looking at sequencer as a conductor, and when looper sees the end of measure, and when the playing position is around the end of recording, it rewinds the position.

The issue sounds like the imported loop was not saved to SD card properly. When you imported the sample, it's on memory. The length was properly stored in the memory, but the sample saved in SD card was shortened for some reason.

**Comment by raspy135** [comment]
I checked the logic. My last guess was wrong, the import looper process import the data to SD card (from import folder to looper00 folder) first, then reload the sample to SD card. 

I'll do some experiment.

**Comment by raspy135** [comment]
I fixed the issue and uploaded 4.05 firmware. Please try it and let me know the result.

**Comment by raspy135** [comment]
Closing
