### ISSUE TITLE
Sequencer Stops by Using Key Combinations with Key "Seq Play"

### ISSUE THREAD

**Issue by artqcid** [raspy135/Qun-mk2#7]
If you use Key Combinations like "Seq/Play + Mode/Play" or any other Combination while Sequencer is running, then the Sequencer stops when releasing this shortcut. I think this should not happen if you use shortcuts with "Seq/Play". Sequencer should only stop if "Seq/Play" is pressed (and released) alone.

**Comment by raspy135** [comment]
This is how it works. It cancels the operation only when you pressed defined key combination, otherwise the operation is not canceled.

**Comment by artqcid** [comment]
But if i tweak the Cut Off with the combination then the Sequencer Stops. So the shortcut for CutOff, VCF Volume etc cannot be used if Sequencer is running. Because the Sequencer stops after i release the shortcut Is that correct?

**Comment by raspy135** [comment]
What key combination did you try? You don't need to press SEQ PLAY to activate the shortcut for Cutoff or any others.
You can use Cutoff or other shortcuts while sequencer is playing.

**Comment by artqcid** [comment]
OMG my fault Sorry
