### ISSUE TITLE
Audio output is LOUD.  Are there work-arounds?

### ISSUE THREAD

**Issue by bptremblay** [raspy135/Qun-mk2#8]
The audio levels are hot. The mixer seems by default to mix to the point of clipping. Polyphony distorts. When I use my headphones my ears hurt. When I plug in 4 Ohm 3W speakers they are super loud. 
Is there a MASTER volume level I can set (and retain) quickly for all tracks? Comparing this to my Novation Circuit or other devices, it has no headroom.

**Comment by raspy135** [comment]
Yes, there is a master volume in system2 menu.
To avoid distortion, adjust VCF volume.

**Comment by raspy135** [comment]
Did the suggestions work for you? If you feel the volume is too low when you set VCF volume to low, then I suggest to enable compressor.

**Comment by raspy135** [comment]
Closing
